# **DIMABSA Project for CSCE 5290**

Domains: English — Restaurant, Laptop
Tasks: DimASR (Regression), DimASTE (Triplet Extraction)

## **GitHub Repo Setup**

In [ ]:
# Forces Colab to use PyTorch
%env TF_CPP_MIN_LOG_LEVEL=3
import os
os.environ["TRANSFORMERS_NO_TF"] = "1"

# Dump default tensorflow
!pip uninstall -y tensorflow tensorflow-gpu

env: TF_CPP_MIN_LOG_LEVEL=3
Found existing installation: tensorflow 2.19.0
Uninstalling tensorflow-2.19.0:
  Successfully uninstalled tensorflow-2.19.0
WARNING: Skipping tensorflow-gpu as it is not installed.

### **Clone the Needed Repos**

In [ ]:
COURSE_URL = "https://github.com/bobjack1313/dimabsa-csce5290.git"
DATASET_URL = "https://github.com/bobjack1313/DimABSA2026.git"

import os

# Create clean work area
os.makedirs("/content/work", exist_ok=True)
%cd /content/work

# Clone the course repo
!git clone "$COURSE_URL" dimabsa-csce5290

# Clone the submodule (dataset) into correct folder
!git clone "$DATASET_URL" dimabsa-csce5290/external/DimABSA2026

# Verify structure
!ls -R /content/work/dimabsa-csce5290 | head -n 50

/content/work
Cloning into 'dimabsa-csce5290'...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 153 (delta 74), reused 97 (delta 30), pack-reused 0 (from 0)
Receiving objects: 100% (153/153), 73.32 KiB | 12.22 MiB/s, done.
Resolving deltas: 100% (74/74), done.
Cloning into 'dimabsa-csce5290/external/DimABSA2026'...
remote: Enumerating objects: 1596, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (181/181), done.
remote: Total 1596 (delta 395), reused 255 (delta 255), pack-reused 1160 (from 2)
Receiving objects: 100% (1596/1596), 5.63 MiB | 11.81 MiB/s, done.
Resolving deltas: 100% (800/800), done.
/content/work/dimabsa-csce5290:
environment.yml
experiments
external
__init__.py
LICENSE
notebooks
pyproject.toml
pytest.ini
README.md
scripts
src
tests
utils

/content/work/dimabsa-csce5290/experiments:

/content/work/dimabsa-csce5290/external:
DimABSA2026

/content/work/dimabsa-csce5290/external/DimABSA2026:
assets
banner.png
continuous TP example.png
evaluation_script
README.md
sample_submission_files
starter_kit
task-dataset
VA.png

/content/work/dimabsa-csce5290/external/DimABSA2026/assets:
continuous_TP_example.png

/content/work/dimabsa-csce5290/external/DimABSA2026/evaluation_script:
metrics_subtask_1_2_3.py
README.md
requirements.txt
sample data

/content/work/dimabsa-csce5290/external/DimABSA2026/evaluation_script/sample data:
subtask_1
subtask_2
subtask_3

/content/work/dimabsa-csce5290/external/DimABSA2026/evaluation_script/sample data/subtask_1:
deu
eng
zho

### **Stage the Data**

In [ ]:
# ---- Stage Raw DimABSA Data (Colab Version of stage_data.py) ----

from pathlib import Path
import shutil

# NOTE: In Colab, we manually define the project root
PROJECT_ROOT = Path("/content/work/dimabsa-csce5290")

# Repo structure is matched exactly
SRC_BASE = PROJECT_ROOT / "external" / "DimABSA2026" / "task-dataset" / "track_a"
OUT_BASE_RAW = PROJECT_ROOT / "data" / "raw"
OUT_BASE_RAW_TASK1 = OUT_BASE_RAW / "task1"
OUT_BASE_RAW_TASK2 = OUT_BASE_RAW / "task2"


def make_dir(path: Path) -> None:
    """Create directory if not exists."""
    path.mkdir(parents=True, exist_ok=True)


def copy_data_to_raw(source_file: Path, dest_file: Path) -> None:
    """Copy a file from external/ to data/raw/ with warnings on missing files."""
    if not source_file.exists():
        print(f"[WARN] Missing expected file: {source_file}")
        return

    dest_file.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(source_file, dest_file)
    print(f"[OK] Copied {dest_file.name}")


def stage_raw_data_task1() -> None:
    print("\n[Task 1] Staging raw files...")
    src = SRC_BASE / "subtask_1" / "eng"

    train_files = [
        "eng_laptop_train_alltasks.jsonl",
        "eng_restaurant_train_alltasks.jsonl",
    ]
    valid_files = [
        "eng_laptop_dev_task1.jsonl",
        "eng_restaurant_dev_task1.jsonl",
    ]

    for fname in train_files + valid_files:
        copy_data_to_raw(src / fname, OUT_BASE_RAW_TASK1 / fname)


def stage_raw_data_task2() -> None:
    print("\n[Task 2] Staging raw files...")
    src = SRC_BASE / "subtask_2" / "eng"

    train_files = [
        "eng_laptop_train_alltasks.jsonl",
        "eng_restaurant_train_alltasks.jsonl",
    ]
    valid_files = [
        "eng_laptop_dev_task2.jsonl",
        "eng_restaurant_dev_task2.jsonl",
    ]

    for fname in train_files + valid_files:
        copy_data_to_raw(src / fname, OUT_BASE_RAW_TASK2 / fname)


def stage_all():
    print("Preparing DimABSA 2026 English raw datasets...")
    stage_raw_data_task1()
    stage_raw_data_task2()
    print("\nAll done!")


# Run the stage operation
stage_all()

Preparing DimABSA 2026 English raw datasets...

[Task 1] Staging raw files...
[OK] Copied eng_laptop_train_alltasks.jsonl
[OK] Copied eng_restaurant_train_alltasks.jsonl
[OK] Copied eng_laptop_dev_task1.jsonl
[OK] Copied eng_restaurant_dev_task1.jsonl

[Task 2] Staging raw files...
[OK] Copied eng_laptop_train_alltasks.jsonl
[OK] Copied eng_restaurant_train_alltasks.jsonl
[OK] Copied eng_laptop_dev_task2.jsonl
[OK] Copied eng_restaurant_dev_task2.jsonl

All done!

## **Preprocessing**

### **Prepare Dataset**

In [ ]:
# ---- Prepare Processed Datasets (Notebook of prepare_datasets.py) ----
from pathlib import Path
import json
import random

# Use fixed path (no __file__)
PROJECT_ROOT = Path("/content/work/dimabsa-csce5290")

# Source and destination dirs
SRC_TASK1 = PROJECT_ROOT / "data" / "raw" / "task1"
SRC_TASK2 = PROJECT_ROOT / "data" / "raw" / "task2"

OUT_TASK1 = PROJECT_ROOT / "data" / "processed" / "task1"
OUT_TASK2 = PROJECT_ROOT / "data" / "processed" / "task2"
OUT_TASK1.mkdir(parents=True, exist_ok=True)
OUT_TASK2.mkdir(parents=True, exist_ok=True)

# Train files
TRAIN_FILES_1 = [
    SRC_TASK1 / "eng_laptop_train_alltasks.jsonl",
    SRC_TASK1 / "eng_restaurant_train_alltasks.jsonl",
]

TRAIN_FILES_2 = [
    SRC_TASK2 / "eng_laptop_train_alltasks.jsonl",
    SRC_TASK2 / "eng_restaurant_train_alltasks.jsonl",
]

# The following functions are from utils/utils_jsonl.py
def parse_stream_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except Exception:
                continue

def write_jsonl(records, path: Path):
    with path.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

# Following functions are in scripts/prepare_datasets.py
def _normalize_quad_list(raw_quads):
    if not isinstance(raw_quads, list):
        return []

    out = []
    for quad in raw_quads:
        if not isinstance(quad, dict):
            continue

        out.append({
            "Aspect": str(quad.get("Aspect", "NULL")),
            "Category": str(quad.get("Category", "NULL")),
            "Opinion": str(quad.get("Opinion", "NULL")),
            "VA": str(quad.get("VA", "NULL")),
        })
    return out


def normalize_task1_record(raw):
    text = raw.get("Text") or ""
    quads = _normalize_quad_list(raw.get("Quadruplet"))

    aspects = [
        q["Aspect"] for q in quads
        if q.get("Aspect") not in (None, "NULL")
    ]

    v = a = None
    if quads:
        va_str = quads[0].get("VA")
        if isinstance(va_str, str) and "#" in va_str:
            try:
                v, a = map(float, va_str.split("#"))
            except:
                pass

    return {
        "ID": raw.get("ID", ""),
        "Text": text,
        "Aspect": aspects,
        "VA_gold": {"V": v, "A": a},
        "Quadruplet": quads,
    }


def normalize_task2_record(raw):
    return {
        "ID": str(raw.get("ID", "")),
        "Text": str(raw.get("Text") or raw.get("text") or ""),
        "Quadruplet": _normalize_quad_list(raw.get("Quadruplet")),
    }


def build_task_split(in_files, normalizer, out_dir, task_name, seed=42):
    print(f"[{task_name}] Loading raw records...")

    all_recs = []
    for src in in_files:
        if not src.exists():
            print(f"[{task_name}] [WARN] Missing file: {src}")
            continue
        print(f"[{task_name}] Reading: {src}")
        for raw in parse_stream_jsonl(src):
            all_recs.append(normalizer(raw))

    total = len(all_recs)
    print(f"[{task_name}] Loaded {total} records.")

    if total == 0:
        print(f"[{task_name}] [ERROR] No data — aborting.")
        return

    random.seed(seed)
    random.shuffle(all_recs)

    split = int(total * 0.8)
    train_recs = all_recs[:split]
    valid_recs = all_recs[split:]

    print(f"[{task_name}] Train: {len(train_recs)} | Valid: {len(valid_recs)}")

    write_jsonl(train_recs, out_dir / "train.jsonl")
    write_jsonl(valid_recs, out_dir / "valid.jsonl")

    print(f"[{task_name}] Wrote train.jsonl and valid.jsonl\n")


# Main for Notebook
def prepare_all():
    print("Preparing processed datasets for DimABSA 2026...\n")

    # Task 1
    build_task_split(
        in_files=TRAIN_FILES_1,
        normalizer=normalize_task1_record,
        out_dir=OUT_TASK1,
        task_name="Task1-DimASR"
    )

    # Task 2
    build_task_split(
        in_files=TRAIN_FILES_2,
        normalizer=normalize_task2_record,
        out_dir=OUT_TASK2,
        task_name="Task2-DimASTE"
    )

    print("[OK] Finished building all processed datasets.")

prepare_all()

Preparing processed datasets for DimABSA 2026...

[Task1-DimASR] Loading raw records...
[Task1-DimASR] Reading: /content/work/dimabsa-csce5290/data/raw/task1/eng_laptop_train_alltasks.jsonl
[Task1-DimASR] Reading: /content/work/dimabsa-csce5290/data/raw/task1/eng_restaurant_train_alltasks.jsonl
[Task1-DimASR] Loaded 6360 records.
[Task1-DimASR] Train: 5088 | Valid: 1272
[Task1-DimASR] Wrote train.jsonl and valid.jsonl

[Task2-DimASTE] Loading raw records...
[Task2-DimASTE] Reading: /content/work/dimabsa-csce5290/data/raw/task2/eng_laptop_train_alltasks.jsonl
[Task2-DimASTE] Reading: /content/work/dimabsa-csce5290/data/raw/task2/eng_restaurant_train_alltasks.jsonl
[Task2-DimASTE] Loaded 6360 records.
[Task2-DimASTE] Train: 5088 | Valid: 1272
[Task2-DimASTE] Wrote train.jsonl and valid.jsonl

[OK] Finished building all processed datasets.

## **Training**

### **Task 1 Training**

In [ ]:
# --- Notebook Version: Train Task 1 (DimASR) ---
# from scripts/train_task1.py
import json
import torch
from pathlib import Path
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
)

# File locations
PROJECT_ROOT = Path("/content/work/dimabsa-csce5290")

# Where processed train/valid splits live
PROC_TASK1 = PROJECT_ROOT / "data" / "processed" / "task1"

# Where checkpoints will be saved
CKPT_BASE = PROJECT_ROOT / "experiments" / "checkpoints" / "task1"
CKPT_BASE.mkdir(parents=True, exist_ok=True)

# Load tasks
def load_task1_notebook():
    splits = {}

    for split in ["train", "valid"]:
        path = PROC_TASK1 / f"{split}.jsonl"
        if not path.exists():
            raise RuntimeError(f"Missing split file: {path}")

        rows = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                rec = json.loads(line)
                gold = rec.get("VA_gold", {})
                v, a = gold.get("V"), gold.get("A")

                # Fallback if missing VA
                if v is None or a is None:
                    rec["labels"] = torch.tensor([5.0, 5.0])
                else:
                    rec["labels"] = torch.tensor([v, a])

                rows.append(rec)

        splits[split] = Dataset.from_list(rows)

    return DatasetDict(splits)


# Tokenizer
def build_preprocess(tokenizer):
    def func(batch):
        enc = tokenizer(
            batch["Text"],
            truncation=True,
            padding="max_length",
            max_length=128,
        )
        return enc
    return func


# Main
def train_task1_notebook(
    arch="bert",
    model_name="bert-base-uncased",
    epochs=3,
    batch_size=8,
    lr=5e-5,
):

    print("[Task1] Loading processed dataset…")
    dataset = load_task1_notebook()
    out_dir = CKPT_BASE

    # Model selection
    if arch == "gpt2":
        model_name = "gpt2"

    print(f"[Task1] Using model: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # GPT-2 needs pad token
    if arch == "gpt2" and tokenizer.pad_token is None:
        tokenizer.add_special_tokens({"pad_token": tokenizer.eos_token})

    preprocess = build_preprocess(tokenizer)
    dataset = dataset.map(preprocess, batched=True)

    # Build regression model (2 outputs: V and A)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2,
        problem_type="regression",
    )

    # GPT-2 resize for pad token
    model.resize_token_embeddings(len(tokenizer))

    # TrainingArguments
    training_args = TrainingArguments(
        output_dir=str(out_dir),
        eval_strategy="epoch",
        do_eval=True,
        learning_rate=lr,
        per_device_train_batch_size=batch_size,
        num_train_epochs=epochs,
        weight_decay=0.01,
        save_total_limit=2,
        logging_dir=str(PROJECT_ROOT / "logs"),
        logging_steps=50,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["valid"],
        tokenizer=tokenizer,
    )

    print("[Task1] Training…")
    trainer.train()

    # Save output under a consistent folder
    out_dir_final = CKPT_BASE / ("task1_gpt2" if arch == "gpt2" else "task1_bert")
    out_dir_final.mkdir(parents=True, exist_ok=True)

    model.save_pretrained(out_dir_final)
    tokenizer.save_pretrained(out_dir_final)

    print(f"[Task1] Saved trained model → {out_dir_final}")
    return out_dir_final

In [ ]:
# Train for BERT
trained_bert = train_task1_notebook(
    arch="bert",
    model_name="bert-base-uncased",
    epochs=3,
    batch_size=8,
    lr=5e-5,
)
print("BERT finished:", trained_bert)
trained_bert

[Task1] Loading processed dataset…
[Task1] Using model: bert-base-uncased

Map:   0%|          | 0/5088 [00:00<?, ? examples/s]

Map:   0%|          | 0/1272 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-3618630180.py:118: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[Task1] Training…

[Task1] Saved trained model → /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert
BERT finished: /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert

PosixPath('/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert')

In [ ]:
# Train for GPT2
trained_gpt2 = train_task1_notebook(
    arch="gpt2",
    model_name="gpt2",
    epochs=3,
    batch_size=8,
    lr=5e-5,
)
print("GPT-2 finished:", trained_gpt2)
trained_gpt2

[Task1] Loading processed dataset…
[Task1] Using model: gpt2

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Map:   0%|          | 0/5088 [00:00<?, ? examples/s]

Map:   0%|          | 0/1272 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-3618630180.py:118: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

[Task1] Training…

[Task1] Saved trained model → /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_gpt2
GPT-2 finished: /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_gpt2

PosixPath('/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_gpt2')

## **Evaluation**

### **Task 1 Predictions**

In [ ]:
# --- Notebook Version: Predict Task 1 (DimASR) ---
# from scripts/predict_task1.py

import json
import torch
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# File dirs
PROJECT_ROOT = Path("/content/work/dimabsa-csce5290")

# JSONL utils from utils/util_jsonl.py
def load_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except:
                continue

def save_jsonl(rows, path: Path):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

# Format VA like "6.75#7.12"
def format_va(v, a):
    return f"{float(v):.4f}#{float(a):.4f}"

def predict_for_aspect(text, model, tokenizer):
    '''
    Run model on the full text. Aspect is NOT appended
    '''
    enc = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=128,
        return_tensors="pt"
    )

    with torch.no_grad():
        logits = model(**enc).logits.cpu().numpy()[0]

    v, a = logits.tolist()
    return v, a

# Main
def predict_task1_notebook(
    model_dir,
    input_path,
    output_path
):

    model_dir = Path(model_dir)
    input_path = Path(input_path)
    output_path = Path(output_path)

    print(f"[Predict] Loading model from {model_dir}…")
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.eval()

    rows_out = []

    print(f"[Predict] Reading input: {input_path}")
    for sample in load_jsonl(input_path):
        sid = sample["ID"]
        text = sample["Text"]
        aspects = sample.get("Aspect", [])

        aspect_va = []
        for asp in aspects:
            v, a = predict_for_aspect(text, model, tokenizer)
            va_str = format_va(v, a)

            aspect_va.append({"Aspect": asp, "VA": va_str})

        rows_out.append({
            "ID": sid,
            "Aspect_VA": aspect_va
        })

    output_path.parent.mkdir(parents=True, exist_ok=True)
    save_jsonl(rows_out, output_path)

    print(f"[OK] Wrote predictions: {output_path}")
    return output_path

### **Make Predictions**

In [ ]:
pred_laptop = predict_task1_notebook(
    model_dir="/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert",
    input_path="/content/work/dimabsa-csce5290/data/raw/task1/eng_laptop_dev_task1.jsonl",
    output_path="/content/work/dimabsa-csce5290/predictions/task1_laptop_dev.jsonl"
)

pred_laptop


pred_rest = predict_task1_notebook(
    model_dir="/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert",
    input_path="/content/work/dimabsa-csce5290/data/raw/task1/eng_restaurant_dev_task1.jsonl",
    output_path="/content/work/dimabsa-csce5290/predictions/task1_restaurant_dev.jsonl"
)

pred_rest

# Combine
import json
from pathlib import Path

ROOT = Path("/content/work/dimabsa-csce5290")

laptop_file = ROOT / "predictions/task1_laptop_dev.jsonl"
restaurant_file = ROOT / "predictions/task1_restaurant_dev.jsonl"
all_file = ROOT / "predictions/task1_dev_all.jsonl"

with all_file.open("w", encoding="utf-8") as f_out:
    # Write laptop predictions
    with laptop_file.open("r", encoding="utf-8") as f:
        for line in f:
            f_out.write(line)

    # Write restaurant predictions
    with restaurant_file.open("r", encoding="utf-8") as f:
        for line in f:
            f_out.write(line)

print("Combined file:", all_file)

[Predict] Loading model from /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert…
[Predict] Reading input: /content/work/dimabsa-csce5290/data/raw/task1/eng_laptop_dev_task1.jsonl
[OK] Wrote predictions: /content/work/dimabsa-csce5290/predictions/task1_laptop_dev.jsonl
[Predict] Loading model from /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert…
[Predict] Reading input: /content/work/dimabsa-csce5290/data/raw/task1/eng_restaurant_dev_task1.jsonl
[OK] Wrote predictions: /content/work/dimabsa-csce5290/predictions/task1_restaurant_dev.jsonl
Combined file: /content/work/dimabsa-csce5290/predictions/task1_dev_all.jsonl

### **Evaluate**

In [ ]:
# --- Notebook Version: Local Evaluation for Task 1 (DimASR) ---
# from scripts/eval_task1.py

import json
import numpy as np
import torch
from pathlib import Path
from scipy.stats import pearsonr
from sklearn.metrics import mean_squared_error
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# File locations
PROJECT_ROOT = Path("/content/work/dimabsa-csce5290")

# JSONL Utility from utils/util_jsonl.py
def load_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    yield json.loads(line)
                except:
                    continue

# Task 1 eval
def eval_task1_local_notebook(model_dir, gold_path, batch_size=16):
    model_dir = Path(model_dir)
    gold_path = Path(gold_path)

    print(f"[Eval] Loading model: {model_dir}")
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.eval()

    gold = list(load_jsonl(gold_path))

    texts = []
    v_gold = []
    a_gold = []

    # Extract VA_gold values
    for ex in gold:
        va = ex.get("VA_gold", {})
        v = va.get("V")
        a = va.get("A")
        if v is None or a is None:
            continue

        texts.append(ex["Text"])
        v_gold.append(float(v))
        a_gold.append(float(a))

    if len(texts) == 0:
        print("ERROR: No usable gold VA labels found.")
        return

    print(f"[Eval] Scoring on {len(texts)} samples (batch size={batch_size})…")

    # Have to use Batching for GPT2
    preds_v = []
    preds_a = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i+batch_size]

        enc = tokenizer(
            batch_texts,
            truncation=True,
            padding=True,
            max_length=128,
            return_tensors="pt"
        )

        with torch.no_grad():
            logits = model(**enc).logits.cpu().numpy()

        preds_v.extend(logits[:, 0].tolist())
        preds_a.extend(logits[:, 1].tolist())

    # RMSE metrics
    v_rmse = mean_squared_error(v_gold, preds_v) ** 0.5
    a_rmse = mean_squared_error(a_gold, preds_a) ** 0.5
    combined_rmse = mean_squared_error(
        v_gold + a_gold,
        preds_v + preds_a
    ) ** 0.5

    # Pearson correlations
    v_pcc = pearsonr(v_gold, preds_v)[0]
    a_pcc = pearsonr(a_gold, preds_a)[0]

    # Output summary
    print("\n=== LOCAL EVALUATION (TASK 1 – DimASR) ===")
    print(f"Samples Used:       {len(texts)}")
    print(f"RMSE (Valence):     {v_rmse:.4f}")
    print(f"RMSE (Arousal):     {a_rmse:.4f}")
    print(f"RMSE (Combined):    {combined_rmse:.4f}")
    print(f"PCC  (Valence):     {v_pcc:.4f}")
    print(f"PCC  (Arousal):     {a_pcc:.4f}")

    return {
        "v_rmse": v_rmse,
        "a_rmse": a_rmse,
        "combined_rmse": combined_rmse,
        "v_pcc": v_pcc,
        "a_pcc": a_pcc,
    }

In [ ]:
# Task - BERT Eval
eval_task1_local_notebook(
    model_dir="/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert",
    gold_path="/content/work/dimabsa-csce5290/data/processed/task1/valid.jsonl"
)

[Eval] Loading model: /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_bert
[Eval] Scoring on 1272 samples…

=== LOCAL EVALUATION (TASK 1 – DimASR) ===
Samples Used:       1272
RMSE (Valence):     0.8392
RMSE (Arousal):     0.7674
RMSE (Combined):    0.8041
PCC  (Valence):     0.8910
PCC  (Arousal):     0.7229

{'v_rmse': 0.8392093125094816,
 'a_rmse': 0.7673897160127086,
 'combined_rmse': 0.804101771518161,
 'v_pcc': np.float64(0.8909721215930552),
 'a_pcc': np.float64(0.7228632040143466)}

In [ ]:
# Task 1 - GPT2 Eval
eval_task1_local_notebook(
    model_dir="/content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_gpt2",
    gold_path="/content/work/dimabsa-csce5290/data/processed/task1/valid.jsonl"
)

[Eval] Loading model: /content/work/dimabsa-csce5290/experiments/checkpoints/task1/task1_gpt2
[Eval] Scoring on 1272 samples (batch size=16)…

=== LOCAL EVALUATION (TASK 1 – DimASR) ===
Samples Used:       1272
RMSE (Valence):     0.8898
RMSE (Arousal):     0.7755
RMSE (Combined):    0.8346
PCC  (Valence):     0.8764
PCC  (Arousal):     0.7192

{'v_rmse': 0.8898006608954787,
 'a_rmse': 0.7754902554939817,
 'combined_rmse': 0.8346048024353058,
 'v_pcc': np.float64(0.8764120128101592),
 'a_pcc': np.float64(0.7191726555135953)}

# **Utility Functions**

In [ ]:
# Use this cell to manipulate project directory and files as needed
# %cd /content/work/dimabsa-csce5290
# !ls

!pwd
!ls -R /content | head -n 50

/content
/content:
sample_data

/content/sample_data:
anscombe.json
california_housing_test.csv
california_housing_train.csv
mnist_test.csv
mnist_train_small.csv
README.md

In [ ]:
# Connect drive to collect outputs
from google.colab import drive
drive.mount('/content/drive')

# Create a symlink to save results
!ln -s /content/drive/MyDrive/dimabsa_outputs /content/work/dimabsa-csce5290/outputs

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ln: failed to create symbolic link '/content/work/dimabsa-csce5290/outputs/dimabsa_outputs': File exists

Both Restaurant and Laptop data verified for DimASR and DimASTE. JSONL structure valid and loads successfully.

## **Evaluation Metric**

In [ ]:
import math

# Example
V_pred, A_pred = 6.75, 6.38
V_true, A_true = 6.0, 6.0
RMSE_VA = math.sqrt(((V_pred - V_true)**2 + (A_pred - A_true)**2) / 128)
print(RMSE_VA)

0.07431457629563663

For DimASTE (continuous F1 concept):
*   cTP = 1 - dist(VA_pred, VA_true) when Aspect + Opinion match.
*   Distance = normalized Euclidean distance in [1, 9] range.

# **Colab to GitHub Commit Cell**
Note:
Keep at bottom of notebook. Also keep commented out until needed.
Must remained uncommented when not used.

## **Copy Current Notebook**

In [ ]:
import os, shutil

# Source notebook (your working one in Drive)
src_path = "/content/drive/MyDrive/Colab Notebooks/csce5290_dimabsa.ipynb"

# Destination path inside your project repo
dst_dir = "/content/work/dimabsa-csce5290/notebooks"
os.makedirs(dst_dir, exist_ok=True)

dst_path = os.path.join(dst_dir, os.path.basename(src_path))

# Copy notebook into repo
if os.path.exists(src_path):
    shutil.copy(src_path, dst_path)
    print(f"Copied notebook to {dst_path}")
else:
    print(f"Notebook not found at {src_path}")

Copied notebook to /content/work/dimabsa-csce5290/notebooks/csce5290_dimabsa.ipynb

## **Stage Changes**

In [ ]:
# Quick Status check - Must run before commit
%cd /content/work/dimabsa-csce5290

#!git add/rm <FILE>
!git status

/content/work/dimabsa-csce5290
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   notebooks/csce5290_dimabsa.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

## **Commit**

In [ ]:
from getpass import getpass

# Configure git (run once per session)
USER_EMAIL = getpass("Enter Email for GitHub Account: ")
USER_NAME = getpass("Enter First and Last Name: ")
!git config --global user.email "$USER_EMAIL"
!git config --global user.name "$USER_NAME"

# --- Stage, commit, and push changes to GitHub ---
# Make sure you're inside your course repo before running:
%cd /content/work/dimabsa-csce5290

# Do not change the echo
echo_message = "Nothing to commit"

# Change this to reflect the work done
# *****  MUST CHANGE *****
commit_message = "Fixed commit messages"

# Uncomment when ready to commit --* re-comment when done *--
!git add .
!git commit -m "$commit_message" || echo "$echo_message"

Enter Email for GitHub Account: ··········
Enter First and Last Name: ··········
/content/work/dimabsa-csce5290
[main 4ab67b7] Fixed commit messages
 1 file changed, 1 insertion(+), 1 deletion(-)

## **Push**

In [ ]:
# Github - Account - Settings - Developer Settings - Create a token -
# 60 days - check repo only - copy token each time - run - then remove it
# Change below to correct user and token each time
PUSH_USER = getpass("Enter GitHub Username: ")
TOKEN = getpass("Enter GitHub Token: ")

# Base repo info (constant) - NO CHANGING
REPO_OWNER = "bobjack1313"
REPO_NAME = "dimabsa-csce5290"

# Set the authenticated remote
!git remote set-url origin \
"https://{PUSH_USER}:{TOKEN}@github.com/{REPO_OWNER}/{REPO_NAME}.git"
!git push origin main

Enter GitHub Username: ··········
Enter GitHub Token: ··········
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.79 KiB | 1.79 MiB/s, done.
Total 8 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 2 local objects.
To https://github.com/bobjack1313/dimabsa-csce5290.git
   4080b63..4ab67b7  main -> main